[package]
name = "termex_api"
version = "0.1.0"
authors = ["sourcepirate <sathyanarrayanan@yandex.com>"]

[dependencies]
keyring = "0.6.0"
reqwest = "0.8.6"
serde = "1.0.70"
serde_derive = "1.0.70"
openssl = "0.10.11"
base64 = "0.9.2"