[package]
name = "termex_cli"
version = "0.1.0"
authors = ["sourcepirate <sathyanarrayanan@yandex.com>"]

[dependencies]
termex_api = {path = "../termex_api"}
docopt = "1.0.0"
serde = "1.0.70"
serde_derive = "1.0.70"
rpassword = "2.0.0"
base64 = "0.9.2"