[package]
name = "termex_import"
version = "0.1.0"
authors = ["sourcepirate <sathyanarrayanan@yandex.com>"]

[dependencies]
termex_api = {path = "../termex_api"}
serde = "1.0.70"
serde_derive = "1.0.70"
docopt = "1.0.0"
chrono = "0.4.6"
base64 = "0.9.2"